# User and Entity Statuses
STATUS_ACTIVE = 1
STATUS_INACTIVE = 0
STATUS_DEACTIVATED = 9

# Pagination Defaults
DEFAULT_PAGE = 1
DEFAULT_PER_PAGE = 10
MAX_PER_PAGE = 1000

# Security Defaults
MIN_PASSWORD_LENGTH = 8
