"""Update RBAC mapping foreign keys to system_modules catalog

Revision ID: 303af261d8b3
Revises: 30de9e7de20a
Create Date: 2026-07-31 18:19:11.809246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '303af261d8b3'
down_revision = '30de9e7de20a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role_permission_mapping', schema=None) as batch_op:
        batch_op.alter_column('role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('module_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('action_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('role_permission_mapping_module_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('role_permission_mapping_action_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'system_modules', ['module_id'], ['id'])
        batch_op.create_foreign_key(None, 'system_module_actions', ['action_id'], ['id'])

    with op.batch_alter_table('user_permission_mapping', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('module_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('action_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('user_permission_mapping_action_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('user_permission_mapping_module_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'system_module_actions', ['action_id'], ['id'])
        batch_op.create_foreign_key(None, 'system_modules', ['module_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_permission_mapping', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('user_permission_mapping_module_id_fkey'), 'modules', ['module_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('user_permission_mapping_action_id_fkey'), 'module_action', ['action_id'], ['id'])
        batch_op.alter_column('status',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('action_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('module_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('role_permission_mapping', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('role_permission_mapping_action_id_fkey'), 'module_action', ['action_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('role_permission_mapping_module_id_fkey'), 'modules', ['module_id'], ['id'])
        batch_op.alter_column('status',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('action_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('module_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('role_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
