"""Add voting system models: voter, election, ballot, candidate, vote, verification, voter_registration

Revision ID: 6769da2d3131
Revises: eaa33ef3f92c
Create Date: 2025-07-10 11:20:10.121665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6769da2d3131'
down_revision = 'eaa33ef3f92c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('elections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('election_code', sa.String(length=50), nullable=False),
    sa.Column('election_type', sa.String(length=50), nullable=False),
    sa.Column('election_category', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('registration_deadline', sa.DateTime(), nullable=True),
    sa.Column('early_voting_start', sa.DateTime(), nullable=True),
    sa.Column('early_voting_end', sa.DateTime(), nullable=True),
    sa.Column('allow_early_voting', sa.Boolean(), nullable=True),
    sa.Column('require_biometric', sa.Boolean(), nullable=True),
    sa.Column('require_photo_id', sa.Boolean(), nullable=True),
    sa.Column('allow_overseas_voting', sa.Boolean(), nullable=True),
    sa.Column('allow_military_voting', sa.Boolean(), nullable=True),
    sa.Column('max_votes_per_voter', sa.Integer(), nullable=True),
    sa.Column('allow_vote_changes', sa.Boolean(), nullable=True),
    sa.Column('require_all_ballots', sa.Boolean(), nullable=True),
    sa.Column('jurisdiction', sa.String(length=100), nullable=True),
    sa.Column('geographic_scope', sa.String(length=100), nullable=True),
    sa.Column('eligible_voter_types', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('is_test_election', sa.Boolean(), nullable=True),
    sa.Column('results_published', sa.Boolean(), nullable=True),
    sa.Column('results_published_at', sa.DateTime(), nullable=True),
    sa.Column('total_registered_voters', sa.Integer(), nullable=True),
    sa.Column('total_votes_cast', sa.Integer(), nullable=True),
    sa.Column('turnout_percentage', sa.Float(), nullable=True),
    sa.Column('election_hash', sa.String(length=255), nullable=True),
    sa.Column('audit_enabled', sa.Boolean(), nullable=True),
    sa.Column('paper_trail_required', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('election_code'),
    sa.UniqueConstraint('election_code', 'company_id', name='unique_election_code_per_company')
    )
    with op.batch_alter_table('elections', schema=None) as batch_op:
        batch_op.create_index('idx_election_dates', ['start_date', 'end_date'], unique=False)
        batch_op.create_index('idx_election_status', ['status', 'is_public'], unique=False)
        batch_op.create_index('idx_election_type', ['election_type', 'election_category'], unique=False)

    op.create_table('ballots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ballot_code', sa.String(length=50), nullable=False),
    sa.Column('ballot_type', sa.String(length=50), nullable=False),
    sa.Column('position_title', sa.String(length=100), nullable=True),
    sa.Column('min_selections', sa.Integer(), nullable=True),
    sa.Column('max_selections', sa.Integer(), nullable=True),
    sa.Column('allow_write_in', sa.Boolean(), nullable=True),
    sa.Column('require_selection', sa.Boolean(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('display_format', sa.String(length=50), nullable=True),
    sa.Column('randomize_candidates', sa.Boolean(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=True),
    sa.Column('jurisdiction_restriction', sa.String(length=100), nullable=True),
    sa.Column('voter_type_restriction', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('is_test_ballot', sa.Boolean(), nullable=True),
    sa.Column('total_votes_cast', sa.Integer(), nullable=True),
    sa.Column('total_eligible_voters', sa.Integer(), nullable=True),
    sa.Column('ballot_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ballot_code', 'election_id', name='unique_ballot_per_election')
    )
    with op.batch_alter_table('ballots', schema=None) as batch_op:
        batch_op.create_index('idx_ballot_election', ['election_id', 'is_active'], unique=False)
        batch_op.create_index('idx_ballot_order', ['election_id', 'order_index'], unique=False)
        batch_op.create_index('idx_ballot_type', ['ballot_type', 'is_published'], unique=False)

    op.create_table('voters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('voter_id', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verification_level', sa.String(length=20), nullable=True),
    sa.Column('phone_verified_at', sa.DateTime(), nullable=True),
    sa.Column('identity_verified_at', sa.DateTime(), nullable=True),
    sa.Column('biometric_verified_at', sa.DateTime(), nullable=True),
    sa.Column('biometric_hash', sa.String(length=255), nullable=True),
    sa.Column('face_encoding_hash', sa.String(length=255), nullable=True),
    sa.Column('registered_device_id', sa.String(length=255), nullable=True),
    sa.Column('device_fingerprint', sa.Text(), nullable=True),
    sa.Column('registered_address', sa.Text(), nullable=True),
    sa.Column('jurisdiction', sa.String(length=100), nullable=True),
    sa.Column('voter_type', sa.String(length=50), nullable=True),
    sa.Column('two_factor_enabled', sa.Boolean(), nullable=True),
    sa.Column('security_pin_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    sa.UniqueConstraint('voter_id'),
    sa.UniqueConstraint('voter_id', 'company_id', name='unique_voter_per_company')
    )
    with op.batch_alter_table('voters', schema=None) as batch_op:
        batch_op.create_index('idx_voter_phone', ['phone_number'], unique=False)
        batch_op.create_index('idx_voter_verification', ['is_verified', 'verification_level'], unique=False)

    op.create_table('candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ballot_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('candidate_code', sa.String(length=50), nullable=False),
    sa.Column('party', sa.String(length=100), nullable=True),
    sa.Column('party_abbreviation', sa.String(length=10), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.Column('platform_summary', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('profile_image_path', sa.String(length=500), nullable=True),
    sa.Column('campaign_website', sa.String(length=200), nullable=True),
    sa.Column('social_media_links', sa.JSON(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('is_write_in', sa.Boolean(), nullable=True),
    sa.Column('is_incumbent', sa.Boolean(), nullable=True),
    sa.Column('is_endorsed', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('years_in_office', sa.Integer(), nullable=True),
    sa.Column('education', sa.String(length=200), nullable=True),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('campaign_finance_id', sa.String(length=50), nullable=True),
    sa.Column('endorsements', sa.Text(), nullable=True),
    sa.Column('key_issues', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_qualified', sa.Boolean(), nullable=True),
    sa.Column('is_withdrawn', sa.Boolean(), nullable=True),
    sa.Column('withdrawal_date', sa.DateTime(), nullable=True),
    sa.Column('withdrawal_reason', sa.String(length=200), nullable=True),
    sa.Column('total_votes_received', sa.Integer(), nullable=True),
    sa.Column('vote_percentage', sa.Float(), nullable=True),
    sa.Column('rank_position', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ballot_id'], ['ballots.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_code', 'ballot_id', name='unique_candidate_per_ballot')
    )
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.create_index('idx_candidate_ballot', ['ballot_id', 'is_active'], unique=False)
        batch_op.create_index('idx_candidate_name', ['name'], unique=False)
        batch_op.create_index('idx_candidate_order', ['ballot_id', 'order_index'], unique=False)
        batch_op.create_index('idx_candidate_party', ['party', 'is_active'], unique=False)

    op.create_table('verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voter_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('verification_id', sa.String(length=100), nullable=False),
    sa.Column('verification_type', sa.String(length=50), nullable=False),
    sa.Column('verification_method', sa.String(length=50), nullable=True),
    sa.Column('verification_data', sa.JSON(), nullable=True),
    sa.Column('verification_hash', sa.String(length=255), nullable=True),
    sa.Column('document_type', sa.String(length=50), nullable=True),
    sa.Column('document_number', sa.String(length=100), nullable=True),
    sa.Column('document_expiry', sa.Date(), nullable=True),
    sa.Column('document_issuer', sa.String(length=100), nullable=True),
    sa.Column('biometric_type', sa.String(length=50), nullable=True),
    sa.Column('biometric_quality_score', sa.Float(), nullable=True),
    sa.Column('biometric_confidence_score', sa.Float(), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('verification_code', sa.String(length=10), nullable=True),
    sa.Column('code_attempts', sa.Integer(), nullable=True),
    sa.Column('max_attempts', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('verification_score', sa.Float(), nullable=True),
    sa.Column('confidence_level', sa.String(length=20), nullable=True),
    sa.Column('initiated_at', sa.DateTime(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.String(length=200), nullable=True),
    sa.Column('external_verification_id', sa.String(length=100), nullable=True),
    sa.Column('external_service', sa.String(length=50), nullable=True),
    sa.Column('external_response', sa.JSON(), nullable=True),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('location_data', sa.JSON(), nullable=True),
    sa.Column('fraud_check_score', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('fraud_indicators', sa.JSON(), nullable=True),
    sa.Column('compliance_checks', sa.JSON(), nullable=True),
    sa.Column('audit_trail', sa.JSON(), nullable=True),
    sa.Column('retention_period', sa.Integer(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=True),
    sa.Column('error_messages', sa.JSON(), nullable=True),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['voter_id'], ['voters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('verification_id')
    )
    with op.batch_alter_table('verifications', schema=None) as batch_op:
        batch_op.create_index('idx_verification_external', ['external_service', 'external_verification_id'], unique=False)
        batch_op.create_index('idx_verification_phone', ['phone_number'], unique=False)
        batch_op.create_index('idx_verification_status', ['status', 'verification_type'], unique=False)
        batch_op.create_index('idx_verification_timestamp', ['initiated_at', 'verified_at'], unique=False)
        batch_op.create_index('idx_verification_voter', ['voter_id', 'verification_type'], unique=False)

    op.create_table('voter_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voter_id', sa.Integer(), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('registration_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('registration_type', sa.String(length=50), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('processed_by', sa.Integer(), nullable=True),
    sa.Column('approval_notes', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.String(length=200), nullable=True),
    sa.Column('eligibility_verified', sa.Boolean(), nullable=True),
    sa.Column('identity_verified', sa.Boolean(), nullable=True),
    sa.Column('address_verified', sa.Boolean(), nullable=True),
    sa.Column('age_verified', sa.Boolean(), nullable=True),
    sa.Column('verification_level_met', sa.String(length=20), nullable=True),
    sa.Column('required_verification_level', sa.String(length=20), nullable=True),
    sa.Column('registered_address', sa.Text(), nullable=True),
    sa.Column('jurisdiction', sa.String(length=100), nullable=True),
    sa.Column('precinct', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('eligible_ballot_types', sa.JSON(), nullable=True),
    sa.Column('ballot_restrictions', sa.JSON(), nullable=True),
    sa.Column('special_accommodations', sa.JSON(), nullable=True),
    sa.Column('preferred_language', sa.String(length=10), nullable=True),
    sa.Column('accessibility_needs', sa.JSON(), nullable=True),
    sa.Column('notification_preferences', sa.JSON(), nullable=True),
    sa.Column('registration_source', sa.String(length=50), nullable=True),
    sa.Column('registration_method', sa.String(length=50), nullable=True),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('location_data', sa.JSON(), nullable=True),
    sa.Column('documents_submitted', sa.JSON(), nullable=True),
    sa.Column('verification_documents', sa.JSON(), nullable=True),
    sa.Column('is_first_time_voter', sa.Boolean(), nullable=True),
    sa.Column('previous_registrations', sa.JSON(), nullable=True),
    sa.Column('voter_history_verified', sa.Boolean(), nullable=True),
    sa.Column('compliance_checks', sa.JSON(), nullable=True),
    sa.Column('audit_trail', sa.JSON(), nullable=True),
    sa.Column('fraud_check_score', sa.Float(), nullable=True),
    sa.Column('risk_assessment', sa.String(length=20), nullable=True),
    sa.Column('notifications_sent', sa.JSON(), nullable=True),
    sa.Column('confirmation_sent', sa.Boolean(), nullable=True),
    sa.Column('reminder_sent', sa.Boolean(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=True),
    sa.Column('error_messages', sa.JSON(), nullable=True),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], ),
    sa.ForeignKeyConstraint(['processed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['voter_id'], ['voters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_id'),
    sa.UniqueConstraint('voter_id', 'election_id', name='unique_registration_per_election')
    )
    with op.batch_alter_table('voter_registrations', schema=None) as batch_op:
        batch_op.create_index('idx_registration_election', ['election_id', 'status'], unique=False)
        batch_op.create_index('idx_registration_geography', ['jurisdiction', 'precinct'], unique=False)
        batch_op.create_index('idx_registration_status', ['status', 'registration_type'], unique=False)
        batch_op.create_index('idx_registration_verification', ['verification_level_met', 'eligibility_verified'], unique=False)
        batch_op.create_index('idx_registration_voter', ['voter_id', 'registered_at'], unique=False)

    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=False),
    sa.Column('ballot_id', sa.Integer(), nullable=False),
    sa.Column('voter_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('vote_id', sa.String(length=100), nullable=False),
    sa.Column('tracking_code', sa.String(length=50), nullable=False),
    sa.Column('vote_data', sa.JSON(), nullable=False),
    sa.Column('encrypted_vote_data', sa.Text(), nullable=True),
    sa.Column('vote_method', sa.String(length=50), nullable=True),
    sa.Column('vote_type', sa.String(length=50), nullable=True),
    sa.Column('is_test_vote', sa.Boolean(), nullable=True),
    sa.Column('vote_hash', sa.String(length=255), nullable=False),
    sa.Column('verification_hash', sa.String(length=255), nullable=False),
    sa.Column('signature_hash', sa.String(length=255), nullable=True),
    sa.Column('biometric_verified', sa.Boolean(), nullable=True),
    sa.Column('device_verified', sa.Boolean(), nullable=True),
    sa.Column('identity_verified', sa.Boolean(), nullable=True),
    sa.Column('two_factor_verified', sa.Boolean(), nullable=True),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('device_fingerprint', sa.Text(), nullable=True),
    sa.Column('app_version', sa.String(length=50), nullable=True),
    sa.Column('operating_system', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('location_data', sa.JSON(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('vote_start_time', sa.DateTime(), nullable=True),
    sa.Column('vote_cast_time', sa.DateTime(), nullable=False),
    sa.Column('vote_processing_time', sa.DateTime(), nullable=True),
    sa.Column('vote_status', sa.String(length=50), nullable=True),
    sa.Column('processing_status', sa.String(length=50), nullable=True),
    sa.Column('is_counted', sa.Boolean(), nullable=True),
    sa.Column('is_auditable', sa.Boolean(), nullable=True),
    sa.Column('receipt_generated', sa.Boolean(), nullable=True),
    sa.Column('receipt_code', sa.String(length=100), nullable=True),
    sa.Column('paper_ballot_id', sa.String(length=100), nullable=True),
    sa.Column('audit_trail', sa.JSON(), nullable=True),
    sa.Column('compliance_verified', sa.Boolean(), nullable=True),
    sa.Column('chain_of_custody', sa.JSON(), nullable=True),
    sa.Column('blockchain_tx_id', sa.String(length=255), nullable=True),
    sa.Column('blockchain_block_number', sa.Integer(), nullable=True),
    sa.Column('blockchain_confirmed', sa.Boolean(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=True),
    sa.Column('error_messages', sa.JSON(), nullable=True),
    sa.Column('warning_flags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ballot_id'], ['ballots.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], ),
    sa.ForeignKeyConstraint(['voter_id'], ['voters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tracking_code'),
    sa.UniqueConstraint('vote_id'),
    sa.UniqueConstraint('voter_id', 'ballot_id', name='unique_vote_per_ballot')
    )
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.create_index('idx_vote_ballot', ['ballot_id', 'is_counted'], unique=False)
        batch_op.create_index('idx_vote_election', ['election_id', 'vote_status'], unique=False)
        batch_op.create_index('idx_vote_status', ['vote_status', 'processing_status'], unique=False)
        batch_op.create_index('idx_vote_timestamp', ['vote_cast_time'], unique=False)
        batch_op.create_index('idx_vote_tracking', ['tracking_code'], unique=False)
        batch_op.create_index('idx_vote_verification', ['verification_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.drop_index('idx_vote_verification')
        batch_op.drop_index('idx_vote_tracking')
        batch_op.drop_index('idx_vote_timestamp')
        batch_op.drop_index('idx_vote_status')
        batch_op.drop_index('idx_vote_election')
        batch_op.drop_index('idx_vote_ballot')

    op.drop_table('votes')
    with op.batch_alter_table('voter_registrations', schema=None) as batch_op:
        batch_op.drop_index('idx_registration_voter')
        batch_op.drop_index('idx_registration_verification')
        batch_op.drop_index('idx_registration_status')
        batch_op.drop_index('idx_registration_geography')
        batch_op.drop_index('idx_registration_election')

    op.drop_table('voter_registrations')
    with op.batch_alter_table('verifications', schema=None) as batch_op:
        batch_op.drop_index('idx_verification_voter')
        batch_op.drop_index('idx_verification_timestamp')
        batch_op.drop_index('idx_verification_status')
        batch_op.drop_index('idx_verification_phone')
        batch_op.drop_index('idx_verification_external')

    op.drop_table('verifications')
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_index('idx_candidate_party')
        batch_op.drop_index('idx_candidate_order')
        batch_op.drop_index('idx_candidate_name')
        batch_op.drop_index('idx_candidate_ballot')

    op.drop_table('candidates')
    with op.batch_alter_table('voters', schema=None) as batch_op:
        batch_op.drop_index('idx_voter_verification')
        batch_op.drop_index('idx_voter_phone')

    op.drop_table('voters')
    with op.batch_alter_table('ballots', schema=None) as batch_op:
        batch_op.drop_index('idx_ballot_type')
        batch_op.drop_index('idx_ballot_order')
        batch_op.drop_index('idx_ballot_election')

    op.drop_table('ballots')
    with op.batch_alter_table('elections', schema=None) as batch_op:
        batch_op.drop_index('idx_election_type')
        batch_op.drop_index('idx_election_status')
        batch_op.drop_index('idx_election_dates')

    op.drop_table('elections')
    # ### end Alembic commands ###
