"""Optimize tenant compound unique constraints and indexes

Revision ID: d10f310cc2c9
Revises: ac7a64b1acd2
Create Date: 2026-07-31 16:41:54.728306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd10f310cc2c9'
down_revision = 'ac7a64b1acd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('elections', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('elections_election_code_key'), type_='unique')
        batch_op.create_index('idx_election_company_status', ['company_id', 'status'], unique=False)

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_one_super_admin_per_company'), postgresql_where='(is_super_admin = true)')

    with op.batch_alter_table('voters', schema=None) as batch_op:
        batch_op.create_index('idx_voter_company_verification', ['company_id', 'is_verified'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voters', schema=None) as batch_op:
        batch_op.drop_index('idx_voter_company_verification')

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_one_super_admin_per_company'), ['company_id'], unique=True, postgresql_where='(is_super_admin = true)')

    with op.batch_alter_table('elections', schema=None) as batch_op:
        batch_op.drop_index('idx_election_company_status')
        batch_op.create_unique_constraint(batch_op.f('elections_election_code_key'), ['election_code'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
